### ISSUE TITLE
Add validation for empty username

### ISSUE THREAD

**Issue by FraDim** [AlchemyOpus/meetup#3]
For older versions of Ecto:
 - https://medium.com/@diamondgfx/testing-validations-in-elixir-and-ecto-677bd8a071a1#.yxhh4ap0l
 - https://hexdocs.pm/ecto/0.2.5/Ecto.Model.Validations.html

**Comment by shabankarumba** [comment]
From https://hexdocs.pm/ecto/2.0.0-beta.1/Ecto.Changeset.html#cast/3
fixed in 3788a0fd535eea5b945d41b28b16b7b8da7d5610
